version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - mynetwork
    ports:
      - "6379:6379"

networks:
  mynetwork:
    driver: bridge
