apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deploy
spec:
  selector:
    matchLabels:
      app: server-kube
  replicas: 3
  template:
    metadata:
      labels:
        app: server-kube
    spec:
      containers:
      - name: springboot-prod-container
        image: rlfgks/bangflix-springboot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
